[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "/que-son-las-yungas"
  to = "/que-son-las-yungas.html"
  status = 200
[[redirects]]
  from = "/mejor-epoca"
  to = "/mejor-epoca.html"
  status = 200
[[redirects]]
  from = "/como-llegar"
  to = "/como-llegar.html"
  status = 200
[[redirects]]
  from = "/precauciones"
  to = "/precauciones.html"
  status = 200
[[redirects]]
  from = "/alojamiento"
  to = "/alojamiento.html"
  status = 200
[[redirects]]
  from = "/presupuesto"
  to = "/presupuesto.html"
  status = 200
[[redirects]]
  from = "/itinerarios"
  to = "/itinerarios.html"
  status = 200
[[redirects]]
  from = "/parque-nacional-calilegua"
  to = "/parque-nacional-calilegua.html"
  status = 200
[[redirects]]
  from = "/termas-rio-jordan"
  to = "/termas-rio-jordan.html"
  status = 200
[[redirects]]
  from = "/fuente-del-jaguar"
  to = "/fuente-del-jaguar.html"
  status = 200
[[redirects]]
  from = "/san-francisco"
  to = "/san-francisco.html"
  status = 200
[[redirects]]
  from = "/santa-ana"
  to = "/santa-ana.html"
  status = 200
[[redirects]]
  from = "/qhapaq-nan"
  to = "/qhapaq-nan.html"
  status = 200
[[redirects]]
  from = "/caspala"
  to = "/caspala.html"
  status = 200
[[redirects]]
  from = "/el-fuerte"
  to = "/el-fuerte.html"
  status = 200
[[redirects]]
  from = "/las-lancitas"
  to = "/las-lancitas.html"
  status = 200
[[redirects]]
  from = "/finca-la-fe"
  to = "/finca-la-fe.html"
  status = 200
[[redirects]]
  from = "/comunidades"
  to = "/comunidades.html"
  status = 200
[[redirects]]
  from = "/fauna"
  to = "/fauna.html"
  status = 200
[[redirects]]
  from = "/directorio"
  to = "/directorio.html"
  status = 200
